---
- name: Install and configure the observability stack
  hosts: observability
  become: true
  roles:
    - w_prometheus
    - w_loki
    - w_grafana
    # - w_alloy   # later on: Log-Shipping

# - name: Harden the target host
#   hosts: target
#   become: true
#   roles:
#     - hardening
    # - w_alloy   # later on: Log-Shipping
