{
 "title": "Detection Lab",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Current Banned IPs",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 4, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (jail) (count_over_time({job=\"fail2ban\", host=\"target\"} |= \"Ban\" [$__auto]))"
    }
   ]
  },
  {
   "title": "Hosts Reachable",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ban & Unban",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 15, "x": 9, "y": 2 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"fail2ban\", host=\"target\"} |= `Ban` [$__auto]))",
     "legendFormat": "Ban"
    },
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"fail2ban\", host=\"target\"} |= `Unban` [$__auto]))",
     "legendFormat": "Unban"
    }
   ]
  },
  {
   "title": "Failed SSH Logins",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 4, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"journald\", host=\"target\", syslog_identifier=\"sshd\"} |~ `Failed password|invalid user` [$__auto]))"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "fail2ban Activity",
   "type": "logs",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"fail2ban\", host=\"target\"} |= ``"
    }
   ]
  },
  {
   "title": "Banned IPs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"fail2ban\", host=\"target\"} |= `Ban `"
    }
   ]
  },
  {
   "title": "sudo Activity",
   "type": "logs",
   "gridPos": { "h": 13, "w": 13, "x": 0, "y": 27 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"journald\", host=\"target\", syslog_identifier=\"sudo\"}"
    }
   ]
  },
  {
   "title": "Account Creation",
   "type": "logs",
   "gridPos": { "h": 13, "w": 11, "x": 13, "y": 27 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"journald\", host=\"target\", syslog_identifier=\"useradd\"}"
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Active Alerts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alert Details",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "ALERTS{alertstate=~\"firing|pending\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}