---
target:
  hosts:
    ubuntu01:
      ansible_host: 10.168.155.10
      ansible_user: target
observability:
  hosts:
    ubuntu02:
      ansible_host: 10.168.155.20
      ansible_user: observability